name: Generate Snake Animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"
  
  # Allow manual execution from the GitHub Actions tab
  workflow_dispatch:
  
  # Run on push to main or master branches
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generates a snake game from a github user's contributions graph, outputs a svg animation
      - name: Generate contribution snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Push the content of build_dir to a branch
      # The submission will be deployed to the output branch
      - name: Push generated SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
